services:
  traefik:
    image: traefik:v2.7
    network_mode: host
    restart: unless-stopped
    command: |
      "--api.dashboard=true"
      "--providers.docker"
      "--providers.docker.exposedbydefault=false"
      "--entrypoints.http.address=:80"
      "--certificatesresolvers.letsencrypt.acme.email=danielrichter@posteo.de"
      "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=desec"
      "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      "--entrypoints.https.address=:443"
      "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      "--entrypoints.http.http.redirections.entrypoint.to=https"
    environment:
      DESEC_TOKEN: aP23NHeZ3t4aCiMSp7sPMcpanRdz
    labels:
      traefik.enable: true
      traefik.http.routers.dashboard.rule: Host(`traefik.dani.rip`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.tls.certresolver: letsencrypt
      traefik.http.services.traefik.loadbalancer.server.port: 8080"
      de.danielr1996.bashdoard.name: Traefik
      de.danielr1996.bashdoard.url: https://traefik.dani.rip/dashboard/
      de.danielr1996.bashdoard.icon: statics/app-logo-128x128.png
      de.danielr1996.bashdoard.id: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik/certs:/data
